# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"Sound": "00_core.ipynb",
         "sine": "00_core.ipynb",
         "FFT": "01_fft.ipynb"}

modules = ["core.py",
           "fft.py"]

doc_url = "https://sizhky.github.io/audio_snippets/"

git_url = "https://github.com/sizhky/audio_snippets/tree/master/"

def custom_doc_links(name): return None
